baseURL = 'https://hfyeh.github.io'
languageCode = 'en-us'
title = 'sharefun'
theme = 'chalk'
ga_analytics = 'UA-56756592-10'
[params]
  mainSections = ['posts']
[params.social]
  github='hfyeh'
  facebook='sharefun010407'
  twitter='SharefunYeh'
[taxonomies]
  tag = "tags"
[params.chalk]
  about_enabled = false
  scrollappear_enabled = true
  theme_toggle = false
